package org.example;

public enum Country
{
    UGANDA("Uganda"),
    UZBEKISTAN("Uzbekistan"),
    AUSTRIA("Austria"),
    AUSTRALIA("Australia"),
    UKRAINE("Ukraine"),
    URUGUAY("Uruguay"),
    AZERBAIJAN("Azerbaijan"),
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    ITALY("Italy"),
    THE_BAHAMAS("The Bahamas"),
    SEYCHELLES("Seychelles"),
    INDONESIA("Indonesia"),
    ICELAND("Iceland"),
    IRAN("Iran"),
    IRELAND("Ireland"),
    EL_SALVADOR("El Salvador"),
    ALBANIA("Albania"),
    ALGERIA("Algeria"),
    ANGOLA("Angola"),
    ANDORRA("Andorra"),
    ESTONIA("Estonia"),
    AFGHANISTAN("Afghanistan"),
    ECUADOR("Ecuador"),
    ARGENTINA("Argentina"),
    ERITREA("Eritrea"),
    ARMENIA("Armenia"),
    UNITED_STATES("United States"),
    ETHIOPIA("Ethiopia"),
    BULGARIA("Bulgaria"),
    BAHRAIN("Bahrain"),
    BELGIUM("Belgium"),
    BELIZE("Belize"),
    BELARUS("Belarus"),
    BANGLADESH("Bangladesh"),
    BRAZIL("Brazil"),
    GEORGIA("Georgia"),
    GHANA("Ghana"),
    GUATEMALA("Guatemala"),
    GUINEA("Guinea"),
    JAMAICA("Jamaica"),
    GERMANY("Germany"),
    GRENADA("Grenada"),
    DENMARK("Denmark"),
    SOUTH_AFRICA("South Africa"),
    MALDIVES("Maldives"),
    INDIA("India"),
    NETHERLANDS("Netherlands"),
    HUNGARY("Hungary"),
    HONDURAS("Honduras"),
    UNITED_KINGDOM("United Kingdom"),
    THE_PHILIPPINES("The Philippines"),
    DOMINICAN_REPUBLIC("The Dominican Republic"),
    VIETNAM("Vietnam"),
    VENEZUELA("Venezuela"),
    ZIMBABWE("Zimbabwe"),
    ZAMBIA("Zambia"),
    IVORY_COAST("Ivory Coast"),
    TURKEY("Turkey"),
    TANZANIA("Tanzania"),
    GREECE("Greece"),
    JAPAN("Japan"),
    JORDAN("Jordan"),
    ISRAEL("Israel"),
    KUWAIT("Kuwait"),
    LEBANON("Lebanon"),
    LIBYA("Libya"),
    LUXEMBOURG("Luxembourg"),
    LATVIA("Latvia"),
    LITHUANIA("Lithuania"),
    MADAGASCAR("Madagascar"),
    MOLDOVA("Moldova"),
    MONGOLIA("Mongolia"),
    MONTENEGRO("Montenegro"),
    MONACO("Monaco"),
    EAST_TIMOR("East Timor"),
    MYANMAR("Myanmar"),
    MALAYSIA("Malaysia"),
    MALTA("Malta"),
    EGYPT("Egypt"),
    NORTH_MACEDONIA("North Macedonia"),
    MEXICO("Mexico"),
    MOROCCO("Morocco"),
    ILLUMINATED("Illuminated"),
    NORWAY("Norway"),
    NIGERIA("Nigeria"),
    NEW_ZEALAND("New Zealand"),
    NAMIBIA("Namibia"),
    NEPAL("Nepal"),
    SUDAN("Sudan"),
    SOMALIA("Somalia"),
    SYRIA("Syria"),
    SIERRA_LEONE("Sierra Leone"),
    CHINA("China"),
    SINGAPORE("Singapore"),
    SLOVENIA("Slovenia"),
    SLOVAKIA("Slovakia"),
    SENEGAL("Senegal"),
    SPAIN("Spain"),
    SERBIA("Serbia"),
    SRI_LANKA("Sri Lanka"),
    OMAN("Oman"),
    IRAQ("Iraq"),
    SAUDI_ARABIA("Saudi Arabia"),
    POLAND("Poland"),
    PORTUGAL("Portugal"),
    FINLAND("Finland"),
    PANAMA("Panama"),
    PAPUA_NEW_GUINEA("Papua New Guinea"),
    PAKISTAN("Pakistan"),
    PARAGUAY("Paraguay"),
    PERU("Peru"),
    CHILE("Chile"),
    CZECH_REPUBLIC("Czech Republic"),
    FRANCE("France"),
    CUBA("Cuba"),
    COLOMBIA("Colombia"),
    COSTA_RICA("Costa Rica"),
    SOUTH_KOREA("South Korea"),
    NORTH_KOREA("North Korea"),
    KAZAKHSTAN("Kazakhstan"),
    LOCOMOTIVE("Locomotive"),
    KYRGYZSTAN("Kyrgyzstan"),
    CAMBODIA("Cambodia"),
    CANADA("Canada"),
    BUY("Buy"),
    CYPRUS("Cyprus"),
    CROATIA("Croatia"),
    VATICAN_CITY("Vatican City"),
    RUMANIA("Rumania"),
    RUSSIA("Russia"),
    REPUBLIC_OF_THE_CONGO("Republic of the Congo"),
    SWEDEN("Sweden"),
    SWITZERLAND("Switzerland"),
    THAILAND("Thailand"),
    TUNISIA("Tunisia"),
    YEMEN("Yemen");

    private final String name;

    Country(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}

